# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "fukuda-abc-terraform-state-dev"
    dynamodb_table = "fukuda-abc-terraform-state-lock-table-dev"
    encrypt        = true
    key            = "us-east-1/lb/terraform.tfstate"
    region         = "us-east-1"
  }
}
