# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "fukuda-abc-terraform-state-stage"
    dynamodb_table = "fukuda-abc-terraform-state-lock-table-stage"
    encrypt        = true
    key            = "us-east-1/network/terraform.tfstate"
    region         = "us-east-1"
  }
}
