# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "fukuda-abc-terraform-state-shared"
    dynamodb_table = "fukuda-abc-terraform-state-lock-table-shared"
    encrypt        = true
    key            = "us-east-1/route53/terraform.tfstate"
    region         = "us-east-1"
  }
}
