# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-1"
  assume_role {
    role_arn = "arn:aws:iam::123456789:role/terragrunt"
  }

  default_tags {
    tags = {
      Environment = "shared"
      Owner       = "Terraform"
    }
  }
}
